### ISSUE TITLE
Loading strapi failed

### ISSUE THREAD

**Issue by 7iomka** [BLYADERUINER/nextjs-strapi-nginx-docker#1]
Hi.
Thanks for this starter
I tried it, but, unfortunatelly

I always have this error, when I running `docker-compose -f development.compose.yml up --build`

![image](https://github.com/BLYADERUINER/nextjs-strapi-nginx-docker/assets/18473137/31b96244-56f9-403f-a510-6b24d3ac0f72)

Am I missing something?
I put .env file in the docker folder with this content

<img width="827" alt="image" src="https://github.com/BLYADERUINER/nextjs-strapi-nginx-docker/assets/18473137/45a58d18-8361-4f4a-a5f3-32773f37f0e0">
but I don't know what exactly values needed here and if they can affect.

**Comment by trydma** [comment]
Hi. The template works if you use your env. 
Here is a link to understand the dependencies. [Strapi Docker](https://docs.strapi.io/dev-docs/installation/docker#development-dockerfile)
I think in your case the problem is with the strapi image or its values in the docker. Try clearing and running the build again.

If that doesn't work, try starting over.
Clone or start a project with a template using your env.

**Comment by 7iomka** [comment]
> Hi. The template works if you use your env. Here is a link to understand the dependencies. [Strapi Docker](https://docs.strapi.io/dev-docs/installation/docker#development-dockerfile) I think in your case the problem is with the strapi image or its values in the docker. Try clearing and running the build again.
> 
> If that doesn't work, try starting over. Clone or start a project with a template using your env.


You are right! It was some strange conflicts between colima and docker desktop on my mac.
I cleaned all paths of docker desktop, and reinstalled colima & docker, and it works like a charm!
Thanks)
